export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CHANGE_USER_INFORMATION = 'CHANGE_USER_INFORMATION';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER = 'REGISTER';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const GET_LIKED_PRODUCTS = 'GET_LIKED_PRODUCTS';
export const ADD_LIKE = 'ADD_LIKE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const REMOVE_LIKE = 'REMOVE_LIKE';

export const GET_PRODUCT_TYPES = 'GET_PRODUCT_TYPES';
export const GET_PRODUCT_BRANDS = 'GET_PRODUCT_BRANDS';
export const GET_BRAND_PRODUCTS = 'GET_BRAND_PRODUCTS';
export const GET_SIMILAR_PRODUCTS = 'GET_SIMILAR_PRODUCTS';
export const GET_POPULAR_PRODUCTS = 'GET_POPULAR_PRODUCTS';
export const GET_MOST_PURCHASED_PRODUCTS = 'GET_MOST_PURCHASED_PRODUCTS';
export const SEARCH_TEXT = 'SEARCH_TEXT';
export const FILTER = 'FILTER';
export const FETCH_SEARCH_RESULT = 'FETCH_SEARCH_RESULT';

// Address
export const GET_ALL_ADDRESSES = 'GET_ALL_ADDRESSES';
export const GET_USER_ADDRESSES = 'GET_USER_ADDRESSES';
export const ADD_USER_ADDRESS = 'ADD_USER_ADDRESS';
export const DELETE_USER_ADDRESS = 'DELETE_USER_ADDRESS';
export const UPDATE_USER_ADDRESS = 'UPDATE_USER_ADDRESS';

// Cart
export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const GET_CART_PRODUCT = 'GET_CART_PRODUCT';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const CHANGE_ITEM_QUANTITY = 'CHANGE_ITEM_QUANTITY';
export const CHANGE_GUEST_ITEM_QUANTITY = 'CHANGE_GUEST_ITEM_QUANTITY';
export const CART_ERROR = 'CART_ERROR';
export const CLEAR_CART_CACHE = 'CLEAR_CART_CACHE';
export const IMPORT_CART_ITEM_FROM_COOKIE = 'IMPORT_CART_ITEM_FROM_COOKIE';

// Guest cart
export const GET_GUEST_CART_ITEMS = 'GET_GUEST_CART_ITEMS';
export const ADD_GUEST_CART_ITEM = 'ADD_GUEST_CART_ITEM';
export const DELETE_GUEST_CART_ITEM = 'DELETE_GUEST_CART_ITEM';
export const CHANGE_GUEST_CART_ITEM = 'CHANGE_GUEST_CART_ITEM';
export const CLEAR_COOKIE = 'CLEAR_COOKIE';

// Order
export const GET_USER_ORDERS = 'GET_USER_ORDERS';
export const ORDER_ERROR = 'ORDER_ERROR';
export const SET_INSTANT_PURCHASE_INFO = 'SET_INSTANT_PURCHASE_INFO';
export const CLEAR_INSTANT_PURCHASE_INFO = 'CLEAR_INSTANT_PURCHASE_INFO';
export const SET_ORDER_ADDRESS = 'SET_ORDER_ADDRESS';
export const MAKE_INSTANT_ORDER = 'MAKE_INSTANT_ORDER';
export const MAKE_ORDER = 'MAKE_ORDER';
export const MAKE_GUEST_ORDER = 'MAKE_GUEST_ORDER';

// Filter product by product type
export const GET_TYPE_PRODUCTS = 'GET_TYPE_PRODUCTS';
// Filter product by product type group
export const GET_TYPE_GROUP_PRODUCTS = 'GET_TYPE_GROUP_PRODUCTS';
